#!/bin/bash

. config/pathes
. config/functions

if [ -d $DIR_SOURCE ]; then
  #  build dir
  if [ -d $DIR_BUILD ]; then
    rm -rf $DIR_BUILD
  fi
  mkdir $DIR_BUILD
  cp -PR $DIR_SOURCE/* $DIR_BUILD

  #  patches
  printf "${green}*** PATHES ***${endcolor}\n"

  cp -PR $DIR_PATCHES/$DIR_MEDIA/* $DIR_BUILD/$DIR_MEDIA
  cp -PR $DIR_PATCHES/$DIR_MEDIA_BUILD/* $DIR_BUILD/$DIR_MEDIA_BUILD

  cd $DIR_BUILD/$DIR_MEDIA
  if ls *.patch 1> /dev/null 2>&1; then
    for f in *.patch; do patch -p1 < "$f"; done
  fi

  cd ../..

  cd $DIR_BUILD/$DIR_MEDIA_BUILD
  if ls *.patch 1> /dev/null 2>&1; then
    for f in *.patch; do patch -p1 < "$f"; done
  fi

  #  build
  printf "${green}*** BUILD ***${endcolor}\n"

  export ${CUR_KERNEL}
  export LDFLAGS=""

  KERNEL_PATH=${BUILD}/build/linux-${CUR_KERNEL}

  make dir DIR=../media
  kernel_make VER=${CUR_KERNEL} SRCDIR=${KERNEL_PATH} allyesconfig
  kernel_make VER=${CUR_KERNEL} SRCDIR=${KERNEL_PATH}

  cd ../..
else
  printf "${red}*** No source dir ***${endcolor}\n"
fi