#!/bin/bash

. config/pathes

if [ "$TYPE_INSTALL" = "modules" ]; then
  if ls $DIR_KERNEL_UPDATES/*.ko 1> /dev/null 2>&1; then
    # uninstall
    printf "${green}*** UNINSTALL ***${endcolor}\n"

    sudo rm -rf $DIR_KERNEL_UPDATES
    sudo depmod -a $CUR_KERNEL
  else
    printf "${red}*** No install ***${endcolor}\n"
  fi
else
  if ls $DIR_KERNEL_UPDATES_EXTRA/* 1> /dev/null 2>&1; then
    # uninstall
    printf "${green}*** UNINSTALL ***${endcolor}\n"

    sudo rm -rf $DIR_KERNEL_UPDATES_EXTRA
    sudo depmod -a $CUR_KERNEL
  else
    printf "${red}*** No install ***${endcolor}\n"
  fi
fi