#!/bin/bash

. config/pathes

if [ "$TYPE_INSTALL" = "modules" ]; then
  if ls $DIR_KERNEL_UPDATES/*.ko 1> /dev/null 2>&1; then
    # uninstall
    printf "${green}*** UNINSTALL ***${endcolor}\n"

    sudo rm -rf $DIR_KERNEL_UPDATES
    sudo depmod
  else
    printf "${red}*** No install ***${endcolor}\n"
  fi
else
  printf "${red}*** Type install not modules ***${endcolor}\n"
fi